model_params:
  name: 'IWAE'
  # dataset: "MNIST"
  # in_channels: 1  # for MNIST
  # latent_dim: 20  # for MNIST
  dataset: "celeba"
  in_channels: 3  # for celeba
  latent_dim: 128  # for celeba
  num_samples: 5  # parameter "k" in the paper


data_set:
  # name: "MNIST"
  name: "celeba"


data_params_MNIST:
  data_path: "Data/"
  train_batch_size: 250
  val_batch_size: 250
  num_workers: 0


data_params_celeba:
  data_path: "Data/"
  train_batch_size: 64
  val_batch_size: 64
  patch_size: 64
  num_workers: 0


exp_params:
  LR: 0.007
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: []
  max_epochs: 10

logging_params:
  save_dir: "logs/"
  name: "IWAE"
